# Generated by Django 5.2 on 2025-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_airplane_rows_alter_airplane_seats_in_row_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat"), name="unique_ticket"
            ),
        ),
    ]
