# Generated by Django 5.2 on 2025-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_remove_ticket_unique_ticket_ticket_unique_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(),
        ),
    ]
