# Generated by Django 5.2 on 2025-05-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_remove_ticket_unique_ticket_ticket_unique_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
